FROM continuumio/miniconda3:4.7.10

LABEL "repository"="https://github.com/jasmcaus/conda-publish"
LABEL "maintainer"="Jason Dsouza <jasmcaus@gmail.com>"

RUN conda install -y anaconda-client conda-build

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]